language: node_js
node_js:
  - 10
script:
  - npm run build:prod
install:
  - npm install
  - npm --prefix "./functions" install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
